# GoReleaser configuration for FerroCP
# See: https://goreleaser.com/customization/

# GoReleaser v1 configuration

# Project metadata
project_name: ferrocp

# Environment variables
env:
  - GO111MODULE=off  # Disable Go modules since this is a Rust project

# Before hooks - run before building
before:
  hooks:
    - echo "🔧 Setting up build environment..."
    - rustup target add x86_64-unknown-linux-gnu
    - rustup target add x86_64-pc-windows-gnu
    - cargo fmt --all -- --check
    - cargo test --workspace --exclude ferrocp-python
    - cargo build --release --bin ferrocp

# Build configuration for Rust binaries
builds:
  - id: ferrocp-linux-amd64
    binary: ferrocp
    main: ./scripts/fake-main.go
    goos: [linux]
    goarch: [amd64]
    hooks:
      post: cp target/release/ferrocp {{ .Path }}

  - id: ferrocp-windows-amd64
    binary: ferrocp
    main: ./scripts/fake-main.go
    goos: [windows]
    goarch: [amd64]
    hooks:
      post: cp target/release/ferrocp.exe {{ .Path }}



# Archive configuration
archives:
  - id: ferrocp-archives
    builds:
      - ferrocp-linux-amd64
      - ferrocp-windows-amd64
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

# Checksum configuration
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
  algorithm: sha256

# Snapshot configuration (for non-tag builds)
snapshot:
  name_template: "{{ .Version }}-next"

# Changelog configuration
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Security"
      regexp: "^.*security[(\\w)]*:+.*$"
      order: 2
    - title: "Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: "Performance"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 4
    - title: "Maintenance"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 5

# GitHub Release configuration
release:
  github:
    owner: loonghao
    name: FerroCP
  name_template: "FerroCP {{ .Version }}"
  prerelease: auto
