# Modern Cargo configuration for FerroCP workspace

[build]
# Use all available CPU cores for compilation (0 means auto-detect)
# jobs = 0  # Commented out to use default behavior

# Enable incremental compilation for faster builds
incremental = true

# Use the sparse registry protocol for faster dependency resolution
[registries.crates-io]
protocol = "sparse"

# Optimize for faster builds in development
[profile.dev]
# Enable some optimizations for dependencies while keeping fast compile times
opt-level = 0
debug = true
split-debuginfo = "unpacked"

# Custom aliases for common tasks
[alias]
# Development aliases
dev-check = "check --workspace --all-targets --all-features"
dev-test = "test --workspace --all-features"
dev-clippy = "clippy --workspace --all-targets --all-features -- -D clippy::correctness -D clippy::suspicious -D clippy::complexity -W clippy::perf -W clippy::style"
dev-fmt = "fmt --all"

# Build aliases
build-all = "build --workspace --all-targets --all-features"
build-release = "build --workspace --release"
build-cli = "build --package ferrocp-cli --release"
build-python = "build --package ferrocp-python --release"

# Testing aliases
test-all = "test --workspace --all-features"
test-unit = "test --workspace --lib"
test-integration = "test --workspace --test '*'"
test-doc = "test --workspace --doc"

# Benchmarking
bench-all = "bench --workspace"
bench-criterion = "bench --package ferrocp-engine"

# Documentation
doc-all = "doc --workspace --all-features --no-deps --open"
doc-private = "doc --workspace --all-features --document-private-items"

# Utility aliases
clean-all = "clean --workspace"
update-deps = "update --workspace"
security-audit = "audit --deny warnings"

# Target-specific configurations
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=-Wl,-rpath,@loader_path"
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=-Wl,-rpath,@loader_path"
]

# Cross-compilation target for Linux ARM64 (VFX Platform)
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-C", "target-cpu=generic",  # Use generic CPU for better compatibility
    "-C", "link-arg=-fuse-ld=lld"
]

# Additional cross-compilation targets
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-C", "target-cpu=generic"]

# Environment variables for development
[env]
RUST_BACKTRACE = "1"
RUST_LOG = "debug"
FERROCP_LOG_LEVEL = "debug"

# VFX Platform cross-compilation environment variables
# These are used when CROSS_COMPILE_ARM64 is set in CI
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER = { value = "aarch64-linux-gnu-gcc", condition = { env = "CROSS_COMPILE_ARM64" } }
CC_aarch64_unknown_linux_gnu = { value = "aarch64-linux-gnu-gcc", condition = { env = "CROSS_COMPILE_ARM64" } }
CXX_aarch64_unknown_linux_gnu = { value = "aarch64-linux-gnu-g++", condition = { env = "CROSS_COMPILE_ARM64" } }
AR_aarch64_unknown_linux_gnu = { value = "aarch64-linux-gnu-ar", condition = { env = "CROSS_COMPILE_ARM64" } }
PKG_CONFIG_ALLOW_CROSS = { value = "1", condition = { env = "CROSS_COMPILE_ARM64" } }

# Blake3 compatibility for cross-compilation
BLAKE3_NO_ASM = { value = "1", condition = { env = "CROSS_COMPILE_ARM64" } }
