name: Build and Deploy Docs

# This workflow builds documentation independently of Rust compilation
# to avoid complex build dependencies and reduce build time from 10-15 minutes to 2-3 minutes

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'README*.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'README*.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install docs dependencies only
        run: |
          python -m pip install --upgrade pip
          pip install sphinx>=7.0.0 pydata-sphinx-theme>=0.14.1

      - name: Build docs (independent of Rust compilation)
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
